//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using SQLite;
using System;

namespace InventoryManager
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<Items>();
                db.CreateTable<User>();
            }
        }
    }
    public partial class Items
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        [NotNull]
        public String ItemID { get; set; }
        
        [NotNull]
        public String ItemName { get; set; }
        
        [NotNull]
        public String ItemDescription { get; set; }
        
    }
    
    public partial class User
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        [NotNull]
        public String Username { get; set; }
        
        [NotNull]
        public String Email { get; set; }
        
        [NotNull]
        public String Password { get; set; }
        
    }
    
}
